# This file was automatically generated by SWIG (http://www.swig.org).
# Version 2.0.11
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.





from sys import version_info
if version_info >= (2,6,0):
    def swig_import_helper():
        from os.path import dirname
        import imp
        fp = None
        try:
            fp, pathname, description = imp.find_module('_Customer', [dirname(__file__)])
        except ImportError:
            import _Customer
            return _Customer
        if fp is not None:
            try:
                _mod = imp.load_module('_Customer', fp, pathname, description)
            finally:
                fp.close()
            return _mod
    _Customer = swig_import_helper()
    del swig_import_helper
else:
    import _Customer
del version_info
try:
    _swig_property = property
except NameError:
    pass # Python < 2.2 doesn't have 'property'.
def _swig_setattr_nondynamic(self,class_type,name,value,static=1):
    if (name == "thisown"): return self.this.own(value)
    if (name == "this"):
        if type(value).__name__ == 'SwigPyObject':
            self.__dict__[name] = value
            return
    method = class_type.__swig_setmethods__.get(name,None)
    if method: return method(self,value)
    if (not static):
        self.__dict__[name] = value
    else:
        raise AttributeError("You cannot add attributes to %s" % self)

def _swig_setattr(self,class_type,name,value):
    return _swig_setattr_nondynamic(self,class_type,name,value,0)

def _swig_getattr(self,class_type,name):
    if (name == "thisown"): return self.this.own()
    method = class_type.__swig_getmethods__.get(name,None)
    if method: return method(self)
    raise AttributeError(name)

def _swig_repr(self):
    try: strthis = "proxy of " + self.this.__repr__()
    except: strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)

try:
    _object = object
    _newclass = 1
except AttributeError:
    class _object : pass
    _newclass = 0


class customer(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, customer, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, customer, name)
    __repr__ = _swig_repr
    def __init__(self): 
        this = _Customer.new_customer()
        try: self.this.append(this)
        except: self.this = this
    __swig_setmethods__["t"] = _Customer.customer_t_set
    __swig_getmethods__["t"] = _Customer.customer_t_get
    if _newclass:t = _swig_property(_Customer.customer_t_get, _Customer.customer_t_set)
    def setCustomerNumber(self, *args): return _Customer.customer_setCustomerNumber(self, *args)
    def getCustomerNumber(self): return _Customer.customer_getCustomerNumber(self)
    def setArrivalTime(self, *args): return _Customer.customer_setArrivalTime(self, *args)
    def getArrivalTime(self): return _Customer.customer_getArrivalTime(self)
    def setTransactionTime(self, *args): return _Customer.customer_setTransactionTime(self, *args)
    def getTransactionTime(self): return _Customer.customer_getTransactionTime(self)
    def setWaitingTime(self, *args): return _Customer.customer_setWaitingTime(self, *args)
    def getWaitingTime(self): return _Customer.customer_getWaitingTime(self)
    __swig_destroy__ = _Customer.delete_customer
    __del__ = lambda self : None;
customer_swigregister = _Customer.customer_swigregister
customer_swigregister(customer)

class task(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, task, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, task, name)
    __repr__ = _swig_repr
    def __init__(self): 
        this = _Customer.new_task()
        try: self.this.append(this)
        except: self.this = this
    def isCheck(self): return _Customer.task_isCheck(self)
    def setCheck(self, *args): return _Customer.task_setCheck(self, *args)
    def isInquiry(self): return _Customer.task_isInquiry(self)
    def setInquiry(self, *args): return _Customer.task_setInquiry(self, *args)
    def isDeposit(self): return _Customer.task_isDeposit(self)
    def setDeposit(self, *args): return _Customer.task_setDeposit(self, *args)
    def isWithdraw(self): return _Customer.task_isWithdraw(self)
    def setWithdraw(self, *args): return _Customer.task_setWithdraw(self, *args)
    def setAmount(self, *args): return _Customer.task_setAmount(self, *args)
    def getAmount(self): return _Customer.task_getAmount(self)
    __swig_destroy__ = _Customer.delete_task
    __del__ = lambda self : None;
task_swigregister = _Customer.task_swigregister
task_swigregister(task)


def setCustomerNumber(*args):
  return _Customer.setCustomerNumber(*args)
setCustomerNumber = _Customer.setCustomerNumber

def getCustomerNumber():
  return _Customer.getCustomerNumber()
getCustomerNumber = _Customer.getCustomerNumber

def setArrivalTime(*args):
  return _Customer.setArrivalTime(*args)
setArrivalTime = _Customer.setArrivalTime

def getArrivalTime():
  return _Customer.getArrivalTime()
getArrivalTime = _Customer.getArrivalTime

def setWaitingTime(*args):
  return _Customer.setWaitingTime(*args)
setWaitingTime = _Customer.setWaitingTime

def getWaitingTime():
  return _Customer.getWaitingTime()
getWaitingTime = _Customer.getWaitingTime

def setTransactionTime(*args):
  return _Customer.setTransactionTime(*args)
setTransactionTime = _Customer.setTransactionTime

def getTransactionTime():
  return _Customer.getTransactionTime()
getTransactionTime = _Customer.getTransactionTime
# This file is compatible with both classic and new-style classes.


