# This file was automatically generated by SWIG (http://www.swig.org).
# Version 2.0.11
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.





from sys import version_info
if version_info >= (2,6,0):
    def swig_import_helper():
        from os.path import dirname
        import imp
        fp = None
        try:
            fp, pathname, description = imp.find_module('_Task', [dirname(__file__)])
        except ImportError:
            import _Task
            return _Task
        if fp is not None:
            try:
                _mod = imp.load_module('_Task', fp, pathname, description)
            finally:
                fp.close()
            return _mod
    _Task = swig_import_helper()
    del swig_import_helper
else:
    import _Task
del version_info
try:
    _swig_property = property
except NameError:
    pass # Python < 2.2 doesn't have 'property'.
def _swig_setattr_nondynamic(self,class_type,name,value,static=1):
    if (name == "thisown"): return self.this.own(value)
    if (name == "this"):
        if type(value).__name__ == 'SwigPyObject':
            self.__dict__[name] = value
            return
    method = class_type.__swig_setmethods__.get(name,None)
    if method: return method(self,value)
    if (not static):
        self.__dict__[name] = value
    else:
        raise AttributeError("You cannot add attributes to %s" % self)

def _swig_setattr(self,class_type,name,value):
    return _swig_setattr_nondynamic(self,class_type,name,value,0)

def _swig_getattr(self,class_type,name):
    if (name == "thisown"): return self.this.own()
    method = class_type.__swig_getmethods__.get(name,None)
    if method: return method(self)
    raise AttributeError(name)

def _swig_repr(self):
    try: strthis = "proxy of " + self.this.__repr__()
    except: strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)

try:
    _object = object
    _newclass = 1
except AttributeError:
    class _object : pass
    _newclass = 0


class task(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, task, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, task, name)
    __repr__ = _swig_repr
    def __init__(self): 
        this = _Task.new_task()
        try: self.this.append(this)
        except: self.this = this
    def isCheck(self): return _Task.task_isCheck(self)
    def setCheck(self, *args): return _Task.task_setCheck(self, *args)
    def isInquiry(self): return _Task.task_isInquiry(self)
    def setInquiry(self, *args): return _Task.task_setInquiry(self, *args)
    def isDeposit(self): return _Task.task_isDeposit(self)
    def setDeposit(self, *args): return _Task.task_setDeposit(self, *args)
    def isWithdraw(self): return _Task.task_isWithdraw(self)
    def setWithdraw(self, *args): return _Task.task_setWithdraw(self, *args)
    def setAmount(self, *args): return _Task.task_setAmount(self, *args)
    def getAmount(self): return _Task.task_getAmount(self)
    __swig_destroy__ = _Task.delete_task
    __del__ = lambda self : None;
task_swigregister = _Task.task_swigregister
task_swigregister(task)


def isCheck():
  return _Task.isCheck()
isCheck = _Task.isCheck

def setCheck(*args):
  return _Task.setCheck(*args)
setCheck = _Task.setCheck

def isInquiry():
  return _Task.isInquiry()
isInquiry = _Task.isInquiry

def setInquiry(*args):
  return _Task.setInquiry(*args)
setInquiry = _Task.setInquiry

def isDeposit():
  return _Task.isDeposit()
isDeposit = _Task.isDeposit

def setDeposit(*args):
  return _Task.setDeposit(*args)
setDeposit = _Task.setDeposit

def isWithdraw():
  return _Task.isWithdraw()
isWithdraw = _Task.isWithdraw

def setWithdraw(*args):
  return _Task.setWithdraw(*args)
setWithdraw = _Task.setWithdraw

def setAmount(*args):
  return _Task.setAmount(*args)
setAmount = _Task.setAmount

def getAmount():
  return _Task.getAmount()
getAmount = _Task.getAmount
# This file is compatible with both classic and new-style classes.


